name: Test & Upload to PyPi

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  test:
    name: 'Test suite'
    uses: ./.github/workflows/test.yml
  build:
    name: 'Build and Publish'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install publishing dependencies
        run: |
          pip install setuptools wheel twine
      - name: Build and Upload to PyPi
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}