name: Test & Upload to PyPi

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: "Installs and upgrades pip, installs other dependencies and installs the package from setup.py"
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          python3 -m pip install pytest
          pytest

      - name: Build and Upload to PyPi
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}